# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do

  pod 'ZXPAutoLayout'
  pod 'MBProgressHUD'
  pod 'AFNetworking'

  target 'DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
